
credit = [
    "Developers",
    "Designers",
    "Programmers",
    "Artists",
    "Sound Designers",
    "Composers",
    "Producers",
    "Directors",
    "Testers",
    "QA Team",
    "Project Managers",
    "Marketing Team",
    "Localization Team",
    "Voice Actors",
    "Motion Capture Artists",
    "Special Thanks",
    "Contributors",
    "Supporters",
    "Community Managers",
    "Graphic Designers",
    "Level Designers",
    "Narrative Designers",
    "Gameplay Designers",
    "Technical Artists",
    "UI/UX Designers",
    "Engineers",
    "Animators",
    "Modelers",
    "Environment Artists",
    "Concept Artists",
    "Scriptwriters",
    "Translators",
    "Legal Advisors",
    "Consultants",
    "Publishers",
    "Distributors",
    "Audio Engineers",
    "Marketing Strategists",
    "Beta Testers",
    "Crowdfunding Backers",
    "Interns",
    "Acknowledgements",
    "Contributing Studios",
    "Quality Assurance",
    "Customer Support",
    "Community Moderators",
    "Playtesters",
    "Localization Specialists",
    "Community Contributors",
    "Technical Support",
    "Voiceover Directors",
    "Audio Producers",
    "Marketing Analysts",
    "Brand Managers",
    "User Researchers",
    "User Interface Artists",
    "Project Coordinators",
    "Production Assistants",
    "System Administrators",
    "Network Engineers",
    "DevOps Engineers",
    "Creative Directors",
    "Game Design Leads",
    "Sound Engineers",
    "Character Artists",
    "Texture Artists",
    "Concept Designers",
    "Voice Casting Directors",
    "Promotional Partners",
    "Public Relations",
    "Social Media Managers",
    "Web Developers",
    "Database Administrators",
    "Artificial Intelligence Specialists",
    "Machine Learning Engineers",
    "Data Scientists",
    "Statistician",
    "Data Analysts",
    "Financial Advisors",
    "Accountants",
    "Investors",
    "Game Testers",
    "Engine Programmers",
    "Audio Programmers",
    "Lead Designers",
    "Lead Programmers",
    "Lead Artists",
    "Lead Writers",
    "Lead Testers",
    "Lead Developers",
    "Lead Engineers",
    "Lead Producers",
    "Lead Directors",
    "Lead Sound Designers",
    "Lead Composers",
    "Lead Graphic Designers",
    "Lead Level Designers",
    "Lead Narrative Designers",
    "Lead Gameplay Designers",
    "Lead Technical Artists",
    "Lead UI/UX Designers",
    "Lead Animators",
    "Lead Modelers",
    "Lead Environment Artists",
    "Lead Concept Artists",
    "Lead Scriptwriters",
    "Lead Translators",
    "Lead Legal Advisors",
    "Lead Consultants",
    "Lead Publishers",
    "Lead Distributors",
    "Lead Audio Engineers",
    "Lead Marketing Strategists",
    "Lead Beta Testers",
    "Lead Crowdfunding Backers",
    "Lead Interns",
    "Lead Acknowledgements",
    "Lead Contributing Studios",
    "Lead Quality Assurance",
    "Lead Customer Support",
    "Lead Community Moderators",
    "Lead Playtesters",
    "Lead Localization Specialists",
    "Lead Community Contributors",
    "Lead Technical Support",
    "Lead Voiceover Directors",
    "Lead Audio Producers",
    "Lead Marketing Analysts",
    "Lead Brand Managers",
    "Lead User Researchers",
    "Lead User Interface Artists",
    "Lead Project Coordinators",
    "Lead Production Assistants",
    "Lead System Administrators",
    "Lead Network Engineers",
    "Lead DevOps Engineers",
    "Lead Creative Directors",
    "Lead Game Design Leads",
    "Lead Sound Engineers",
    "Lead Character Artists",
    "Lead Texture Artists",
    "Lead Concept Designers",
    "Lead Voice Casting Directors",
    "Lead Promotional Partners",
    "Lead Public Relations",
    "Lead Social Media Managers",
    "Lead Web Developers",
    "Lead Database Administrators",
    "Lead Artificial Intelligence Specialists",
    "Lead Machine Learning Engineers",
    "Lead Data Scientists",
    "Lead Statistician",
    "Lead Data Analysts",
    "Lead Financial Advisors",
    "Lead Accountants",
    "Lead Investors",
    "Lead Game Testers",
    "Lead Engine Programmers",
    "Lead Audio Programmers",
    "Volunteers",
    "Contractors",
    "Contributing Artists",
    "Contributing Musicians",
    "Contributing Writers",
    "Contributing Programmers",
    "Contributing Designers",
    "Contributing Engineers",
    "Contributing Producers",
    "Contributing Directors",
    "Contributing Testers",
    "Contributing QA Team",
    "Contributing Project Managers",
    "Contributing Marketing Team",
    "Contributing Localization Team",
    "Contributing Voice Actors",
    "Contributing Motion Capture Artists",
    "Contributing Special Thanks",
    "Contributing Contributors",
    "Contributing Supporters",
    "Contributing Community Managers",
    "Contributing Graphic Designers",
    "Contributing Level Designers",
    "Contributing Narrative Designers",
    "Contributing Gameplay Designers",
    "Contributing Technical Artists",
    "Contributing UI/UX Designers",
    "Contributing Engineers",
    "Contributing Animators",
    "Contributing Modelers",
    "Contributing Environment Artists",
    "Contributing Concept Artists",
    "Contributing Scriptwriters",
    "Contributing Translators",
    "Contributing Legal Advisors",
    "Contributing Consultants",
    "Contributing Publishers",
    "Contributing Distributors",
    "Contributing Audio Engineers",
    "Contributing Marketing Strategists",
    "Contributing Beta Testers",
    "Contributing Crowdfunding Backers",
    "Contributing Interns",
    "Contributing Acknowledgements",
    "Contributing Contributing Studios",
    "Contributing Quality Assurance",
    "Contributing Customer Support",
    "Contributing Community Moderators",
    "Contributing Playtesters",
    "Contributing Localization Specialists",
    "Contributing Community Contributors",
    "Contributing Technical Support",
    "Contributing Voiceover Directors",
    "Contributing Audio Producers",
    "Contributing Marketing Analysts",
    "Contributing Brand Managers",
    "Contributing User Researchers",
    "Contributing User Interface Artists",
    "Contributing Project Coordinators",
    "Contributing Production Assistants",
    "Contributing System Administrators",
    "Contributing Network Engineers",
    "Contributing DevOps Engineers",
    "Contributing Creative Directors",
    "Contributing Game Design Leads",
    "Contributing Sound Engineers",
    "Contributing Character Artists",
    "Contributing Texture Artists",
    "Contributing Concept Designers",
    "Contributing Voice Casting Directors",
    "Contributing Promotional Partners",
    "Contributing Public Relations",
    "Contributing Social Media Managers",
    "Contributing Web Developers",
    "Contributing Database Administrators",
    "Contributing Artificial Intelligence Specialists",
    "Contributing Machine Learning Engineers",
    "Contributing Data Scientists",
    "Contributing Statistician",
    "Contributing Data Analysts",
    "Contributing Financial Advisors",
    "Contributing Accountants",
    "Contributing Investors",
    "Contributing Game Testers",
    "Contributing Engine Programmers",
    "Contributing Audio Programmers",
    "Based on a concept by",
    "Powered by",
    "Technology provided by",
    "Licensed from",
    "Original Soundtrack by",
    "Powered by Unreal Engine",
    "Powered by Unity",
    "Special thanks to",
    "Based on characters created by",
    "Ported by",
    "Developed with the support of",
    "Lead Developer",
    "Lead Designer",
    "Lead Artist",
    "Lead Programmer",
    "Lead Sound Designer",
    "Lead Composer",
    "Lead Producer",
    "Lead Director",
    "Based on a story by",
    "Based on an idea by",
    "Original idea by",
    "Inspired by",
    "Character designs by",
    "Character animations by",
    "Level designs by",
    "Environment designs by",
    "Gameplay mechanics by",
    "Narrative written by",
    "Soundtrack composed by",
    "Additional music by",
    "Additional programming by",
    "Additional art by",
    "Additional design by",
    "Additional sound design by",
    "Additional support from",
    "Translations by",
    "Legal support by",
    "Consulting by",
    "Publishing by",
    "Distributed by",
    "Audio production by",
    "Marketing by",
    "Market research by",
    "UI/UX design by",
    "Additional testing by",
    "Community management by",
    "Promotions by",
    "Public relations by",
    "Web development by",
    "Database management by",
    "AI implementation by",
    "Machine learning by",
    "Data analysis by",
    "Financial management by",
    "Accounting by",
    "Investment by",
    "Localization by",
    "Community support by",
    "Server management by",
    "Network management by",
    "DevOps by",
    "Creative direction by",
    "Game design by",
    "Sound engineering by",
    "Additional character art by",
    "Additional environment art by",
    "Additional concept art by",
    "Voice casting by",
    "Promotional partnerships by",
    "Social media management by",
    "QA supervision by",
    "Playtesting coordination by",
    "Contributing partners",
    "Powered by custom engine",
    "Powered by in-house technology",
    "Developed in collaboration with"
]